### ISSUE TITLE
Logging notes on drawers inserts drawers in wrong place when refiling

### ISSUE THREAD

**Issue by ericsfraga** [m-cat/org-recur#3] opened 2019-12-13 16:32 UTC
If I invoke org-recur-finish and I've requested logging of tasks (org-log-done set to 'note'), the note created and the associated LOGBOOK drawer are inserted elsewhere in the file after the task has been filed away in the archive.

**Comment by mrcnski** [comment] 2019-12-13 18:38
I haven't used drawers. Do you have detailed steps for reproducing your problem? What is your configuration?

As far as archiving goes, this package basically just uses the provided org commands `org-archive-subtree` and `org-agenda-archive`. I would be quite surprised if this package was interfering with your workflow, but I would have to see your configuration.

**Comment by ericsfraga** [comment] 2019-12-13 20:27
Thanks for the quick response.

I think the only thing I have set is as above (`org-log-done`). I'll have a look at the code later to see what it is that might be affecting this. What it seems to me to be happening is that the tree is archived *before* the task is noted as DONE so that by the time the log note is created, the entry is no longer in the original file/buffer.

**Comment by ericsfraga** [comment] 2019-12-13 20:36
I'll add that I have set both `org-recur-finish-archive` and `org-recur-finish-done` to t. Your code looks like it does things in the right order so I am quite puzzled. May need to learn the elisp debugger finally!

**Comment by mrcnski** [comment] 2019-12-13 22:06
Yeah, I see what you mean. I'm able to reproduce this now.

> Your code looks like it does things in the right order so I am quite puzzled.

Me too! It works fine when I call `org-todo` followed by `org-archive-subtree` using the individual commands, but when I call `org-recur-finish` the behavior is indeed different.

Actually, I realized why this happens. When `org-log-done` is set to `'note`, calling `org-todo` causes a prompt to come up asking for a closing note. When calling `org-recur-finish`, the two commands are executed without waiting for a closing note to be entered. I'll have to think if there's any good solution to this...

**Comment by ericsfraga** [comment] 2019-12-14 00:37
Ah, that makes sense. Thanks for figuring out what is going wrong. I hope you can find a solution but it's not a deal breaker and I'm finding this package very useful. Thank you.

**Comment by mrcnski** [comment] 2019-12-16 16:07
The problem is that when the prompt for the closing note comes up, the user can go off and do other things before entering the note, so I don't see an elegant way of handling this. So far the only solution I could think of is checking if `org-log-done` is set to `'note` and not archiving automatically in that case, perhaps printing a warning message if `org-recur-finish-archive` is set to `t`. 

> I hope you can find a solution but it's not a deal breaker and I'm finding this package very useful. Thank you.

I'm happy you like it. Thanks for reporting this!

**Comment by mrcnski** [comment] 2019-12-16 23:51
I pushed a commit containing the patch as described above, let me know what you think. I'll leave this issue open in case I or somebody else comes up with a better solution.

**Comment by ericsfraga** [comment] 2019-12-17 10:44
Thank you.

I am, however, confused. No matter what I do, I get prompted for the log information for state change from "" to "DONE". There must be something in my configuration although I have set all variables I can see related to this to nil. Very strange.

**Comment by mrcnski** [comment] 2019-12-17 10:59
Have you inspected the output of `C-h v org-log-done` in an org buffer?

**Comment by ericsfraga** [comment] 2019-12-17 11:00
Yes, and it is nil, which is why I am confused!

**Comment by ericsfraga** [comment] 2019-12-18 14:57
Solved my confusion: I had org-goto-keywords set to require a note and that seems to override any other setting. I have set a file specific set of TODO keywords and everything works fine now. Thank you!

**Closed as completed** 2021-10-05 02:15 UTC
